APP 	:= my_app
TESTAPP	:= test
MAIN 	:= main.cpp
CCFLAGS := -Wall -pedantic -std=c++17
CFLAGS 	:= -Wall -pedantic -std=c99
CC 		:= g++
C 		:= gcc
SRC 	:= src
TEST	:= test
OBJTEST	:= obj_test
OBJ 	:= obj
BIN		:= bin
INCL	:= include
TEMP	:= template
LIBS	:= 
LIBSTEST:= -lgtest -lpthread
INCDIRS	:= -I$(SRC) -I$(INCL) -I$(TEMP)

include ./.next/*.mk

#Yours Rules